# render.yaml – Blueprint para monorepo
services:
  - type: web
    name: mts-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm ci
      npm run prisma:generate
      npx prisma migrate deploy
      npm run build
    startCommand: node dist/main.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENABLE_SWAGGER
        value: "false"
      - key: NODE_ENV
        value: "production"

  - type: static
    name: mts-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        # aponta para o backend do Render (depois de criado, edita este valor no painel)
        value: https://mts-backend.onrender.com
